using Content.Client.UserInterface.Controls;
using Content.Shared._Sirius.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Sirius.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PipBoyMusicUiFragment : BoxContainer
{
    public event Action<string>? OnTrackSelected;
    public event Action? OnPlayPressed;
    public event Action? OnPausePressed;
    public event Action? OnStopPressed;
    public event Action? OnToggleRepeat;
    public event Action? OnToggleAutoNext;

    private List<PipBoyMusicTrack> _allTracks = new();
    private string? _selectedId;
    private bool _isPlaying;
    private bool _updatingFromState;
    private float _sliderLockTimer;

    public PipBoyMusicUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        SearchBar.OnTextChanged += _ => RebuildTrackList();

        PlayPauseButton.OnPressed += _ =>
        {
            if (_isPlaying)
                OnPausePressed?.Invoke();
            else
                OnPlayPressed?.Invoke();
        };

        StopButton.OnPressed += _ => OnStopPressed?.Invoke();

        RepeatCheckBox.OnToggled += _ =>
        {
            if (_updatingFromState)
                return;
            OnToggleRepeat?.Invoke();
        };

        AutoNextCheckBox.OnToggled += _ =>
        {
            if (_updatingFromState)
                return;
            OnToggleAutoNext?.Invoke();
        };

        PlaybackSlider.OnReleased += _ =>
        {
            PipBoyMusicClientSystem.Instance?.SeekTo(PlaybackSlider.Value);
            _sliderLockTimer = 0.5f;
        };
    }

    public void UpdateState(PipBoyMusicUiState state)
    {
        _allTracks = state.Tracks;
        _selectedId = state.SelectedTrackId;
        _isPlaying = state.IsPlaying;

        PlayPauseButton.Text = _isPlaying
            ? Loc.GetString("pipboy-music-button-pause")
            : Loc.GetString("pipboy-music-button-play");
        _updatingFromState = true;
        if (RepeatCheckBox.Pressed != state.RepeatOne)
            RepeatCheckBox.Pressed = state.RepeatOne;
        if (AutoNextCheckBox.Pressed != state.AutoNext)
            AutoNextCheckBox.Pressed = state.AutoNext;
        _updatingFromState = false;

        RebuildTrackList();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_sliderLockTimer > 0f)
            _sliderLockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _sliderLockTimer > 0f;

        var info = PipBoyMusicClientSystem.Instance?.GetPlaybackInfo() ?? (0f, 0f, false, false);

        if (info.HasStream && info.Length > 0f)
        {
            PlaybackSlider.MaxValue = info.Length;
            if (!PlaybackSlider.Grabbed && _sliderLockTimer <= 0f)
                PlaybackSlider.SetValueWithoutEvent(info.Position);

            DurationLabel.Text =
                $"{TimeSpan.FromSeconds(info.Position):mm\\:ss} / {TimeSpan.FromSeconds(info.Length):mm\\:ss}";
        }
        else
        {
            if (!PlaybackSlider.Grabbed && _sliderLockTimer <= 0f)
                PlaybackSlider.SetValueWithoutEvent(0f);

            DurationLabel.Text = "00:00 / 00:00";
        }
    }

    private void RebuildTrackList()
    {
        TrackList.RemoveAllChildren();
        var query = SearchBar.Text?.Trim() ?? string.Empty;

        foreach (var track in _allTracks)
        {
            if (query.Length > 0 &&
                track.Name.IndexOf(query, StringComparison.OrdinalIgnoreCase) < 0 &&
                track.Id.IndexOf(query, StringComparison.OrdinalIgnoreCase) < 0)
                continue;

            var selected = track.Id == _selectedId;
            var button = new Button
            {
                Text = selected ? $"▶ {track.Name}" : track.Name,
                HorizontalExpand = true,
                ToggleMode = false,
                ClipText = true,
            };

            var trackId = track.Id;
            button.OnPressed += _ => OnTrackSelected?.Invoke(trackId);
            TrackList.AddChild(button);
        }
    }
}
