- type: startingGear
  id: RaiderPistolGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    shoes: N14ClothingShoesRaider
    mask: N14ClothingMaskBrownMask
    head: N14ClothingHeadHatTribalOutcastHood
    hands: ClothingHandsGlovesFingerless
    outerClothing: N14ClothingOuterLightMetalArmor
    pocket1: N14RaiderStash

- type: startingGear
  id: RaiderHunterGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBrahminFarmer
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatArmyCap
    mask: N14ClothingMaskBlackMask
    hands: N14ClothingHandsGlovesCloth
    outerClothing: N14ClothingOuterCoatLeatherDuster
    pocket1: N14RaiderStash

- type: startingGear
  id: RaiderSkrimisherGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    shoes: N14ClothingBootsLeather
    head: ClothingHeadHelmetBone
    hands: N14ClothingHandsGlovesCloth
    outerClothing: N14ClothingOuterRaiderBlastmaster
    pocket1: N14RaiderStash

- type: startingGear
  id: RaiderBossGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitSettlerRags
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatBeanie
    mask: SiriusClothingSkullMask
    outerClothing: N14ClothingOuterRaiderCombat1
    pocket1: N14RaiderStash

- type: startingGear
  id: FernMercPrivateGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatArmyCap
    mask: N14ClothingMaskBrownMask
    outerClothing: N14ClothingOuterVestLeather
    pocket1: N14RaiderStash

- type: startingGear
  id: FernMercSergeantGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    shoes: N14ClothingBootsBlack
    head: N14ClothingHeadHatCombatHelmet
    mask: ClothingMaskBandSkull
    hands: ClothingHandsGlovesMercFingerless
    eyes: N14ClothingEyesGlassesWelding
    outerClothing: N14ClothingOuterCombatArmor
    belt: ClothingBeltMilitary
    pocket1: N14RaiderStash

- type: startingGear
  id: FernMercLieutenantGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    shoes: N14ClothingBootsCombat
    head: N14ClothingHeadHatArmyBeret
    neck: N14ClothingNeckCloakGhillie
    hands: ClothingHandsGlovesMercFingerless
    eyes: N14ClothingEyesSunGlasses
    outerClothing: N14ClothingOuterCombatArmorMK2
    pocket1: N14RaiderStash

- type: startingGear
  id: EnforcerTrooperGear
  equipment:
    jumpsuit: N14ClothingUniformRangerVeteranBlack
    shoes: N14ClothingBootsFire
    head: ClothingHeadHelmetBasic
    mask: ClothingMaskNeckGaiter
    outerClothing: N14ClothingOuterPoliceVest
    eyes: ClothingEyesGlassesSunglassesAviator
    hands: N14ClothingHandsGlovesBlackBiker
    pocket1: N14RaiderStash

- type: startingGear
  id: EnforcerWardenGear
  equipment:
    jumpsuit: N14ClothingUniformRangerVeteranBlack
    shoes: N14ClothingBootsCombat
    mask: ClothingMaskBandSkull
    head: N14ClothingHeadHatCombatHelmetMK2
    hands: N14ClothingHandsGlovesBlackBiker
    outerClothing: N14ClothingOuterPoliceVest
    pocket1: N14RaiderStash

- type: startingGear
  id: EnforcerChiefGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitPreWarManager
    shoes: N14ClothingBootsCombatMK2
    head: ClothingHeadHatCapcap
    eyes: N14ClothingEyesSunGlasses
    outerClothing: N14ClothingOuterPoliceChief
    pocket1: N14RaiderStash

#MARK: Melee

- type: startingGear
  id: EnforcerBeatcopGear
  equipment:
    jumpsuit: N14ClothingUniformRangerVeteranBlack
    shoes: N14ClothingBootsFire
    hands: N14ClothingHandsGlovesBlackBiker
    mask: ClothingMaskNeckGaiter
    eyes: ClothingEyesGlassesSunglassesAviator
    head: N14ClothingHeadHatVaultRiot
    outerClothing: N14ClothingOuterPoliceVest
    pocket1: N14RaiderStash
    pocket2: Handcuffs
  inhand:
  - N14PoliceBaton
  - N14ShieldMetalLight

- type: startingGear
  id: FernConscriptGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    mask: N14ClothingMaskRedMask
    eyes: N14ClothingEyesSunGlasses
    shoes: N14ClothingBootsLeather
    hands: N14ClothingHandsGlovesBlackBiker
    head: N14ClothingHeadHatArmyCap
    pocket1: N14RaiderStash
  inhand:
  - N14TrenchClub

- type: startingGear
  id: PsychoRaiderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    eyes: N14ClothingEyesGlassesWelding
    shoes: N14ClothingShoesRaider
    head: ClothingHeadHatBeanieGreen
    hands: N14ClothingHandsGlovesCloth
    mask: N14ClothingMaskBrownBalaclava
    outerClothing: M14ClothingOuterArmorKitPunk
    pocket1: N14RaiderStash
  inhand:
  - N14KitchenKnife

- type: startingGear
  id: VaultRaiderRangedGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMechanic
    shoes: N14ClothingBootsBlack
    head: SiriusClothingHeadHatRaiderVaultRiot
    mask: N14ClothingMaskBlackBalaclava
    outerClothing: SiriusClothingOuterVaultRaiderSecVest
    pocket1: N14RaiderStash

- type: startingGear
  id: GlowingPsihGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuittribalpantsm
    shoes: N14ClothingShoesRaider
    head: N14ClothingHeadHatHoodPonchoCloak
    outerClothing: M14ClothingOuterArmorKit
    pocket1: N14RaiderStash
  inhand:
  - N14HuntingKnifeSirius

- type: startingGear
  id: ratcannibalgear
  equipment:
    jumpsuit: N14ClothingUniformDesertPants
    shoes: N14ClothingShoesTribal
    outerClothing: N14ClothingOuterRaiderBadlands
    pocket1: N14RaiderStash
    pocket2: FoodMeatHuman
  inhand:
  - N14TribalKnife

- type: startingGear
  id: ZavodchaninTagilaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOliveSweater
    mask: N14ClothingMaskBrownBalaclava
    shoes: MisfitsMilitarySteelTippedBoots
    hands: N14ClothingHandsGlovesBlackLeather
    outerClothing: N14ClothingScavengerHeavyArmor
    head: ClothingHeadHatWelding
    pocket1: N14RaiderStash

- type: startingGear
  id: ZavodchaninElectricGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitEngineeringHazard
    shoes: ClothingShoesBootsWork
    hands: ClothingHandsGlovesColorYellowBudget
    outerClothing: N14ClothingOuterMetalArmor
    head: ClothingHeadHatHardhatYellowDark
    eyes: N14ClothingEyesGlassesWelding
    pocket1: N14RaiderStash

- type: startingGear
  id: ZavodchaninSlesarGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitFlannelOveralls
    shoes: N14ClothingBootsFire
    outerClothing: M14ClothingOuterArmorKit
    head: N14ClothingHeadHatBaseball
    mask: N14ClothingMaskBrownBalaclava
    hands: N14ClothingHandsGlovesBlackBiker
    pocket1: N14RaiderStash
  inhand:
  - N14Wrench

- type: startingGear
  id: ZavodchaninDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarianZav
    shoes: ClothingShoesBootsLaceup
    outerClothing: N14ClothingOuterVaultSecVest
    head: ClothingHeadHatHardhatArmored
    pocket1: N14RaiderStash
    pocket2: DrinkMugOne
  inhand:
  - N14Whip
  - BoxFolderClipboard

- type: startingGear
  id: ZavodchaninMechanGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMechanic
    shoes: N14ClothingBootsBlack
    outerClothing: N14ClothingOuterWinterRaider
    head: SiriusClothingHeadHatRaiderVaultRiot
    belt: N14ScrapMachete
    pocket1: N14RaiderStash

- type: startingGear
  id: KochGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitSettlerRags
    shoes: N14ClothingShoesRags
    mask: N14ClothingMaskSheriff
    eyes: ClothingEyesGlassesChemist
    head: N14ClothingHeadHatVaultBlueprintHelmetMetal
    outerClothing: M14ClothingOuterArmorKitPunk
    pocket1: N14RaiderStash
  inhand:
  - N14HuntingKnifeSirius

- type: startingGear
  id: KochGearShot
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitSettlerRags
    shoes: N14ClothingShoesRags
    head: ClothingHeadHatStrawHat
    hands: N14ClothingHandsGlovesTribal
    outerClothing: M14ClothingOuterArmorKitShoulder
    pocket1: N14RaiderStash
