using Content.Client.UserInterface.Controls;
using Content.Shared._Nuclear14.AutodocSirius;
using Content.Shared._Shitmed.Targeting;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;

namespace Content.Client._Nuclear14.AutodocSirius;

[GenerateTypedNameReferences]
public sealed partial class SiriusAutodocWindow : DefaultWindow
{
    private static readonly Color ColorMinor = Color.FromHex("#33FF33");
    private static readonly Color ColorModerate = Color.FromHex("#FFAA33");
    private static readonly Color ColorSevere = Color.FromHex("#FF5533");
    private static readonly Color ColorCritical = Color.FromHex("#FF3333");
    private static readonly Color ColorDim = Color.FromHex("#1a5c1a");
    private static readonly Color ColorActive = Color.FromHex("#33FF33");
    private static readonly Color ColorInactive = Color.FromHex("#3a5c3a");
    private static readonly Color ColorDisabled = Color.FromHex("#444444");
    private static readonly Color ColorSevered = Color.FromHex("#666666");
    private static readonly Color ColorHealthy = Color.FromHex("#33FF33");

    private readonly Dictionary<string, string> _damageDisplayNames = new()
    {
        { "Blunt", Loc.GetString("autodoc-damage-blunt") },
        { "Slash", Loc.GetString("autodoc-damage-slash") },
        { "Piercing", Loc.GetString("autodoc-damage-piercing") },
        { "Heat", Loc.GetString("autodoc-damage-heat") },
        { "Cold", Loc.GetString("autodoc-damage-cold") },
        { "Shock", Loc.GetString("autodoc-damage-shock") },
        { "Caustic", Loc.GetString("autodoc-damage-caustic") },
        { "Radiation", Loc.GetString("autodoc-damage-radiation") },
        { "Bloodloss", Loc.GetString("autodoc-damage-bloodloss") },
        { "Asphyxiation", Loc.GetString("autodoc-damage-asphyxiation") },
        { "Poison", Loc.GetString("autodoc-damage-poison") },
        { "Toxins", Loc.GetString("autodoc-damage-toxins") },
        { "Genetic", Loc.GetString("autodoc-damage-genetic") },
        { "Cellular", Loc.GetString("autodoc-damage-cellular") }
    };

    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IResourceCache _cache;
    private EntityUid _spriteViewEntity;
    private static readonly EntProtoId BodyView = "AlertSpriteView";
    private static readonly ISawmill _sawmill = Logger.GetSawmill("autodoc");

    public event Action<AutodocUiButton>? OnAutodocButton;
    public event Action<AutodocSurgeryButton, string?>? OnSurgeryButton;

    public SiriusAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("autodoc-window-title");

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _cache = dependencies.Resolve<IResourceCache>();

        ApplyBackgroundStyles();
        WireButtons();
        SetInitialButtonStates();
        OnClose += () => OnAutodocButton?.Invoke(AutodocUiButton.Close);

        HeadButton.Visible = false;
        ChestButton.Visible = false;
        GroinButton.Visible = false;
        LeftArmButton.Visible = false;
        LeftHandButton.Visible = false;
        RightArmButton.Visible = false;
        RightHandButton.Visible = false;
        LeftLegButton.Visible = false;
        LeftFootButton.Visible = false;
        RightLegButton.Visible = false;
        RightFootButton.Visible = false;
    }

    private void ApplyBackgroundStyles()
    {
        var brightLine = new StyleBoxFlat(Color.FromHex("#1a5c1a"));
        var dimLine = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepTop.PanelOverride = brightLine;
        SepMid1.PanelOverride = dimLine;
        SepMid2.PanelOverride = dimLine;
        SepMid3.PanelOverride = dimLine;
        SepMid4.PanelOverride = dimLine;
        SepBottom.PanelOverride = dimLine;
        SepHumanoid.PanelOverride = dimLine;
    }

    private void WireButtons()
    {
        DoorOpenButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.OpenDoor);
        DoorCloseButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.CloseDoor);
        EjectBeakerButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectBeaker);
        EjectPatientButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectPatient);
        StartTreatmentButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.StartTreatment);
        SurgeryAllButton.OnPressed += _ => OnSurgeryButton?.Invoke(AutodocSurgeryButton.StartAll, null);
    }

    private void SetInitialButtonStates()
    {
        EjectBeakerButton.Disabled = true;
        EjectPatientButton.Disabled = true;
        StartTreatmentButton.Disabled = true;
        SurgeryAllButton.Disabled = true;
        SurgeryPanel.Visible = false;
        SurgeryProgressContainer.Visible = false;

        EjectBeakerButton.ModulateSelfOverride = ColorInactive;
        EjectPatientButton.ModulateSelfOverride = ColorInactive;
        StartTreatmentButton.ModulateSelfOverride = ColorInactive;
        SurgeryAllButton.ModulateSelfOverride = ColorInactive;
    }

    public void UpdateState(AutodocBoundUserInterfaceState state)
    {
        UpdatePatientInfo(state);
        UpdateDamageDisplay(state);
        UpdateHumanoidDoll(state);
        UpdateSurgeryPanel(state);
        UpdateStimulantsDisplay(state);
        UpdateDoorButtonsState(state);
        UpdateActionButtonsState(state);
        UpdateProgressDisplay(state);
        UpdateFooter(state);
    }

    private void UpdateSurgeryPanel(AutodocBoundUserInterfaceState state)
    {
        if (!state.HasOccupant || !state.CanSurgery)
        {
            SurgeryPanel.Visible = false;
            return;
        }

        SurgeryPanel.Visible = true;
        var isLocked = state.IsOpen || state.IsTreating;
        SurgeryAllButton.Disabled = isLocked;
        SurgeryAllButton.ModulateSelfOverride = isLocked ? ColorInactive : null;

        foreach (var child in SurgeryListContainer.Children)
        {
            if (child is Button btn)
            {
                btn.Disabled = isLocked;
                btn.ModulateSelfOverride = isLocked ? ColorInactive : null;
            }
        }
    }
    private void UpdateAvailablePartsList(AutodocBoundUserInterfaceState state)
    {
        AvailablePartsContainer.RemoveAllChildren();

        if (!state.CanSurgery || state.OccupantDamage == null)
        {
            var label = new Label
            {
                Text = Loc.GetString("autodoc-surgery-no-parts"),
                FontColorOverride = ColorDim,
                StyleClasses = { "monospace" }
            };
            AvailablePartsContainer.AddChild(label);
            return;
        }
    }
    private void UpdatePatientInfo(AutodocBoundUserInterfaceState state)
    {
        if (state.HasOccupant && !string.IsNullOrEmpty(state.OccupantName))
        {
            PatientNameLabel.Text = state.OccupantName.ToUpperInvariant();
            PatientNameLabel.FontColorOverride = ColorActive;

            var statusText = state.OccStatus switch
            {
                OccupantStatus.Alive => Loc.GetString("autodoc-status-alive"),
                OccupantStatus.Critical => Loc.GetString("autodoc-status-critical"),
                OccupantStatus.Dead => Loc.GetString("autodoc-status-dead"),
                _ => Loc.GetString("autodoc-status-unknown")
            };

            StatusLabel.Text = statusText;
            StatusLabel.FontColorOverride = state.OccStatus switch
            {
                OccupantStatus.Alive => ColorMinor,
                OccupantStatus.Critical => ColorModerate,
                OccupantStatus.Dead => ColorCritical,
                _ => ColorDim
            };
        }
        else
        {
            PatientNameLabel.Text = Loc.GetString("autodoc-no-patient");
            PatientNameLabel.FontColorOverride = ColorDim;
            StatusLabel.Text = Loc.GetString("autodoc-status-awaiting");
            StatusLabel.FontColorOverride = ColorDim;
        }
    }

    private void UpdateDamageDisplay(AutodocBoundUserInterfaceState state)
    {
        DamageContainer.RemoveAllChildren();

        if (!state.HasOccupant)
        {
            var emptyLabel = MakeDiagnosticLine(Loc.GetString("autodoc-damage-no-patient"), ColorDim);
            DamageContainer.AddChild(emptyLabel);
            return;
        }

        if (state.OccupantDamage == null || state.OccupantDamage.Count == 0)
        {
            var emptyLabel = MakeDiagnosticLine(Loc.GetString("autodoc-damage-none"), ColorDim);
            DamageContainer.AddChild(emptyLabel);
            return;
        }

        var maxDamage = state.OccupantDamage.Values.Max(x => x.Float());
        maxDamage = Math.Max(maxDamage, 100f);

        var sortedDamage = state.OccupantDamage
            .OrderByDescending(x => x.Value.Float())
            .ToList();

        foreach (var kvp in sortedDamage)
        {
            var damageType = kvp.Key;
            var amount = kvp.Value;

            if (amount <= 0) continue;

            var displayName = _damageDisplayNames.GetValueOrDefault(damageType, damageType.ToUpperInvariant());
            var color = GetDamageColor(amount.Float());

            DamageContainer.AddChild(MakeDamageLine(displayName, amount.Float(), color, maxDamage));
        }
    }

    private BoxContainer MakeDamageLine(string damageName, float amount, Color color, float maxDamage)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2)
        };

        var nameLabel = new Label
        {
            Text = $"[ {damageName} ]",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 140
        };

        var barBg = new PanelContainer
        {
            MinWidth = 120,
            MinHeight = 12,
            HorizontalExpand = false,
            PanelOverride = new StyleBoxFlat(Color.FromHex("#1a3a1a"))
        };

        var barWidth = 120f * Math.Clamp(amount / maxDamage, 0.05f, 1f);
        var fillPanel = new PanelContainer
        {
            MinWidth = barWidth,
            MinHeight = 12,
            PanelOverride = new StyleBoxFlat(color)
        };
        barBg.AddChild(fillPanel);

        var amountLabel = new Label
        {
            Text = $"{amount:F0}",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 50,
            HorizontalAlignment = HAlignment.Right
        };

        container.AddChild(nameLabel);
        container.AddChild(barBg);
        container.AddChild(amountLabel);

        return container;
    }

    private Label MakeDiagnosticLine(string text, Color color)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 8, 0, 8)
        };
    }

    private Color GetDamageColor(float amount)
    {
        if (amount >= 75) return ColorCritical;
        if (amount >= 50) return ColorSevere;
        if (amount >= 25) return ColorModerate;
        if (amount > 0) return ColorMinor;
        return ColorDim;
    }

    private EntityUid? SetupIcon(AutodocBoundUserInterfaceState state)
    {
        var bodyStatus = new Dictionary<TargetBodyPart, TargetIntegrity>();

        if (state.OccupantDamage != null && state.OccupantDamage.Count > 0)
        {
            var allParts = new[]
            {
                TargetBodyPart.Head, TargetBodyPart.Torso, TargetBodyPart.Groin,
                TargetBodyPart.LeftArm, TargetBodyPart.LeftHand,
                TargetBodyPart.RightArm, TargetBodyPart.RightHand,
                TargetBodyPart.LeftLeg, TargetBodyPart.LeftFoot,
                TargetBodyPart.RightLeg, TargetBodyPart.RightFoot
            };

            var totalDamage = state.OccupantDamage.Values.Sum(x => x.Float());

            foreach (var part in allParts)
            {
                bodyStatus[part] = totalDamage switch
                {
                    >= 75 => TargetIntegrity.CriticallyWounded,
                    >= 50 => TargetIntegrity.HeavilyWounded,
                    >= 25 => TargetIntegrity.ModeratelyWounded,
                    >= 10 => TargetIntegrity.LightlyWounded,
                    _ => TargetIntegrity.Healthy
                };
            }
        }
        else
        {
            var allParts = new[]
            {
                TargetBodyPart.Head, TargetBodyPart.Torso, TargetBodyPart.Groin,
                TargetBodyPart.LeftArm, TargetBodyPart.LeftHand,
                TargetBodyPart.RightArm, TargetBodyPart.RightHand,
                TargetBodyPart.LeftLeg, TargetBodyPart.LeftFoot,
                TargetBodyPart.RightLeg, TargetBodyPart.RightFoot
            };
            foreach (var part in allParts)
            {
                bodyStatus[part] = TargetIntegrity.Healthy;
            }
        }

        if (bodyStatus.Count == 0)
            return null;

        if (!_entityManager.Deleted(_spriteViewEntity))
            _entityManager.QueueDeleteEntity(_spriteViewEntity);

        _spriteViewEntity = _entityManager.Spawn(BodyView);

        if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
            return null;

        var spriteEnt = new Entity<SpriteComponent?>(_spriteViewEntity, sprite);

        int layer = 0;
        foreach (var (bodyPart, integrity) in bodyStatus)
        {
            string enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
            int enumValue = (int) integrity;

            var rsi = new SpriteSpecifier.Rsi(
                new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi"),
                $"{enumName.ToLowerInvariant()}_{enumValue}");

            if (!_spriteSystem.TryGetLayer(spriteEnt, layer, out _, false))
                _spriteSystem.AddTextureLayer(spriteEnt, _spriteSystem.Frame0(rsi));
            else
                _spriteSystem.LayerSetTexture(spriteEnt, layer, _spriteSystem.Frame0(rsi));

            _spriteSystem.LayerSetScale(spriteEnt, layer, new Vector2(3f, 3f));
            layer++;
        }

        return _spriteViewEntity;
    }

    private void UpdateHumanoidDoll(AutodocBoundUserInterfaceState state)
    {
        if (!state.HasOccupant)
        {
            HumanoidContainer.Visible = false;
            SepHumanoid.Visible = false;
            DollStatusLabel.Text = "НЕТ ПАЦИЕНТА";
            DollStatusLabel.FontColorOverride = ColorInactive;
            SurgeryPanel.Visible = false;
            return;
        }

        HumanoidContainer.Visible = true;
        SepHumanoid.Visible = true;

        var spriteEntity = SetupIcon(state);
        if (spriteEntity != null)
        {
            DollSpriteView.SetEntity(spriteEntity);
        }

        var totalDamage = state.OccupantDamage?.Values.Sum(x => x.Float()) ?? 0;
        var statusText = totalDamage switch
        {
            0 => "ВСЕ КОНЕЧНОСТИ ЦЕЛЫ",
            < 25 => "ЛЁГКИЕ ПОВРЕЖДЕНИЯ",
            < 50 => "СРЕДНИЕ ПОВРЕЖДЕНИЯ",
            < 75 => "ТЯЖЁЛЫЕ ПОВРЕЖДЕНИЯ",
            _ => "КРИТИЧЕСКИЕ ПОВРЕЖДЕНИЯ"
        };

        DollStatusLabel.Text = statusText;
        DollStatusLabel.FontColorOverride = totalDamage switch
        {
            0 => ColorMinor,
            < 25 => Color.FromHex("#88FF44"),
            < 50 => ColorModerate,
            < 75 => ColorSevere,
            _ => ColorCritical
        };
    }

    private void UpdateStimulantsDisplay(AutodocBoundUserInterfaceState state)
    {
        if (state.HasBeaker)
        {
            var amount = state.BeakerStimulantsAmount.Float();
            StimulantsLabel.Text = $"{amount:F1}";
            StimulantsLabel.FontColorOverride = amount >= 30 ? ColorMinor : ColorModerate;
        }
        else
        {
            StimulantsLabel.Text = Loc.GetString("autodoc-stimulants-none");
            StimulantsLabel.FontColorOverride = ColorDim;
        }
    }

    private void UpdateDoorButtonsState(AutodocBoundUserInterfaceState state)
    {
        var disabled = state.IsTreating;

        DoorOpenButton.Disabled = disabled || state.IsOpen;
        DoorCloseButton.Disabled = disabled || !state.IsOpen;

        DoorOpenButton.ModulateSelfOverride = (disabled || state.IsOpen) ? ColorInactive : null;
        DoorCloseButton.ModulateSelfOverride = (disabled || !state.IsOpen) ? ColorInactive : null;

        DoorOpenButton.Text = state.IsOpen ? Loc.GetString("autodoc-door-open") : Loc.GetString("autodoc-door-open-button");
        DoorCloseButton.Text = !state.IsOpen ? Loc.GetString("autodoc-door-closed") : Loc.GetString("autodoc-door-close-button");
    }

    private void UpdateActionButtonsState(AutodocBoundUserInterfaceState state)
    {
        var ejectPatientDisabled = !state.HasOccupant || state.IsTreating || !state.IsOpen;
        var ejectBeakerDisabled = !state.HasBeaker || state.IsTreating;
        var startDisabled = !state.TreatButtonEnabled || state.IsTreating || state.IsOpen;

        EjectBeakerButton.Disabled = ejectBeakerDisabled;
        EjectPatientButton.Disabled = ejectPatientDisabled;
        StartTreatmentButton.Disabled = startDisabled;

        EjectBeakerButton.ModulateSelfOverride = ejectBeakerDisabled ? ColorInactive : null;
        EjectPatientButton.ModulateSelfOverride = ejectPatientDisabled ? ColorInactive : null;
        StartTreatmentButton.ModulateSelfOverride = startDisabled ? ColorInactive : null;

        StartTreatmentButton.Text = state.IsTreating
            ? Loc.GetString("autodoc-treatment-progress")
            : Loc.GetString("autodoc-start-treatment");
    }

    private void UpdateProgressDisplay(AutodocBoundUserInterfaceState state)
    {
        if (state.IsTreating && state.TreatmentProgress > 0)
        {
            ProgressContainer.Visible = true;
            TreatmentProgress.Value = state.TreatmentProgress * 100;
            ProgressPercentLabel.Text = $"{state.TreatmentProgress * 100:F0}%";
        }
        else
        {
            ProgressContainer.Visible = false;
            TreatmentProgress.Value = 0;
            ProgressPercentLabel.Text = "0%";
        }
    }

    private void UpdateFooter(AutodocBoundUserInterfaceState state)
    {
        if (state.IsTreating)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-treatment");
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (!state.Powered)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-no-power");
            FooterLabel.FontColorOverride = ColorCritical;
        }
        else if (state.HasOccupant && state.IsOpen)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-door-open");
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (state.HasOccupant && !state.TreatButtonEnabled)
        {
            var required = 30;
            var current = state.BeakerStimulantsAmount.Float();
            FooterLabel.Text = Loc.GetString("autodoc-footer-insufficient-stimulants",
                ("required", required),
                ("current", current));
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (state.HasOccupant && !state.IsOpen)
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-ready");
            FooterLabel.FontColorOverride = ColorMinor;
        }
        else
        {
            FooterLabel.Text = Loc.GetString("autodoc-footer-ready");
            FooterLabel.FontColorOverride = ColorDim;
        }
    }
}

public enum AutodocSurgeryButton
{
    StartAll,
    SurgeryPart,
    EjectPart,
    Close
}
